name: Test
on: [push]
jobs:
  Test-Simple-Commands:
    runs-on: ubuntu-latest
    env: 
      DEVICE: poco_m3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: download tools
        run: |
            source source_me.sh
            dt
      - name: kernel download + build
        run: |
            source source_me.sh
            kd && kb
