name: Test
on: [push]
jobs:
  Test-Simple-Commands:
    runs-on: ubuntu-latest
    env: 
      DEVICE: poco_m3
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: download tools
        run: |
            source source_me.sh
            dt
      - name: kernel download + build
        run: |
            source source_me.sh
            kd && kb
      - name: rom download
        run: |
            source source_me.sh
            rd
      - name: boot.img extract and repack
        run: |
            source source_me.sh
            be && br
      - name: kernel download + build + rom download + boot.img extract + boot.img repack 
        run: |
            source source_me.sh
            kd && kb && rd && be && br
